### ISSUE TITLE
Blank when running on Linux 64-bit

### ISSUE THREAD

**Issue by kokizzu** [kinvolk/headlamp#232] opened 2021-03-30 13:40 UTC
**Description**

running the AppImage, shows a blank window with logs:
```
20:34:28.837 › App starting...
Checking for update
20:34:29.270 › Sending status to window: Checking for update...
../../third_party/tcmalloc/chromium/src/free_list.cc:135] Memory corruption detected. 
20:34:29.454 › server process stdout: *** Headlamp Server ***
  API Routers:
        localhost:4466/clusters/kis@kubernetes/{api...} -> https://xy-kubernetes:6443

20:34:29.455 › server process stderr: 2021/03/30 20:34:29 plugins-dir: /home/k_xy/.config/Headlamp/plugins

../../third_party/tcmalloc/chromium/src/free_list.cc:135] Memory corruption detected. 
../../third_party/tcmalloc/chromium/src/free_list.cc:135] Memory corruption detected. 
Update for version 0.3.0-beta1 is not available (latest version: 0.3.0-beta1, downgrade is disallowed).
20:34:30.498 › Sending status to window: Update not available.
checkForUpdatesAndNotify called, downloadPromise is null
20:34:34.929 › stopping server process...
```

**Impact**

can't use this program

**Environment and steps to reproduce**

1. **Set-up**: download `./Headlamp-0.3.0-beta1-linux-x64.AppImage` from [release](https://kinvolk.io/docs/headlamp/0.3/installation/desktop/linux-installation/) page
2. **Task**: just opening the program
3. **Action(s)**: -
4. **Error**: as above

**Expected behavior**
no error

**Additional information**
`Linux G4560 5.4.0-51-generic #56-Ubuntu SMP Mon Oct 5 14:28:49 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by kokizzu** [comment] 2021-03-31 05:06
```
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.2 LTS
Release:        20.04
Codename:       focal
```

**Comment by illume** [comment] 2021-04-07 18:36
Hello,

I haven't been able to reproduce this yet. There are two options you could try to work around it however.

The first is you can run the headlamp app with the GUI inside the browser:
```bash
headlamp --headless
```

The second runs without GPU enabled (only in Headlamp 0.3.0):
```bash
headlamp --disable-gpu
```

**Comment by joaquimrocha** [comment] 2021-04-29 10:33
Hi @kokizzu ,

This week we've published Headlamp as a [Flatpak](https://flathub.org/apps/details/io.kinvolk.Headlamp) too.
Can you check whether running it as a flatpak helps you get to the UI?

**Comment by kokizzu** [comment] 2021-04-29 12:17
![image](https://user-images.githubusercontent.com/1061610/116549276-7b247800-a91f-11eb-8ea5-f54d1bb04846.png)

**Comment by joaquimrocha** [comment] 2021-04-29 15:52
@kokizzu , you may need to install Flatpak on Ubuntu before: https://flatpak.org/setup/Ubuntu/

**Comment by joaquimrocha** [comment] 2021-06-28 10:43
I am closing this issue since there has been no further feedback, and in our tests in Ubuntu things have been working correctly.
@kokizzu , if you're still experiencing this, please reopen and provide more details.

**Closed by joaquimrocha** 2021-06-28 10:43 UTC
